### ISSUE TITLE
Add a namespace paramater to connect()

### ISSUE THREAD

**Issue by rstuart85** [Kapiche/gcloud-datastore-oem#2]
Google Datastore supports multi-tenancy via [namespaces](https://cloud.google.com/datastore/docs/concepts/entities). Building that directly into the connect call will allow us to emulate different "databases" within Datastore. Such a feature is useful for keeping a Dev datastore and a production datastore for example.

**Comment by macexon** [comment]
Is this an answer to my previous question - or just something I was not
meant to be copied on 'cos would not comprehend it........

On Thu, Apr 30, 2015 at 6:35 AM, Ryan Stuart <notifications@github.com>
wrote:

> Google Datastore supports multi-tenancy via namespaces
> <https://cloud.google.com/datastore/docs/concepts/entities>. Building
> that directly into the connect call will allow us to emulate different
> "databases" within Datastore. Such a feature is useful for keeping a Dev
> datastore and a production datastore for example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kapiche/gcloud-datastore-oem/issues/2>.
>



-- 
*Mac Exon-Taylor*
CEO, Co-Founder

*Kapiche Ltd*
mac@kapiche.com
+44 (0) 7460 170 907
*www.kapiche.com <http://www.kapiche.com>*

**Comment by rstuart85** [comment]
Neither. It's something you get notified off because you are automatically subscribed to all Kapiche repos. On the github page, top right, click the unwatch button.

**Comment by macexon** [comment]
Thanks, will do.  I needed to clarify the Trending and Data Storage
elements in the Competitor table.  We don't offer Topic trending right now;
granted we can provide the data to do it - if that is what you meant?
Equally, I was not sure if the Data Storage item referred to the underlying
Data mining/indexing platform, or simply a capability of the API?

Also, I thought we were advocating sentiment at the Topic level, not
comment, so perhaps ticking both boxes negates our argument?


On Thu, Apr 30, 2015 at 8:20 AM, Ryan Stuart <notifications@github.com>
wrote:

> Neither. It's something you get notified off because you are automatically
> subscribed to all Kapiche repos. On the github page, top right, click the
> unwatch button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kapiche/gcloud-datastore-oem/issues/2#issuecomment-97691991>
> .
>



-- 
*Mac Exon-Taylor*
CEO, Co-Founder

*Kapiche Ltd*
mac@kapiche.com
+44 (0) 7460 170 907
*www.kapiche.com <http://www.kapiche.com>*
